"""Initial Migration

Revision ID: 0e0be7ab081d
Revises: c03d3b89a800
Create Date: 2020-09-24 03:56:11.988061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0be7ab081d'
down_revision = 'c03d3b89a800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'title')
    # ### end Alembic commands ###
